-- idx_positions_vessel_ts_asc: an ascending (vessel_id, ts) index on
-- positions, alongside the existing idx_positions_vessel_ts (vessel_id,
-- ts DESC) from schema.sql.
--
-- Motivation: normalizer/rederive.py's per-chunk positions query is
-- `ORDER BY vessel_id, ts` (ascending, matching the chronological order
-- its per-vessel state-carry logic needs). The existing DESC index can't
-- serve that order, so PostgreSQL falls back to a disk-spilling sort on
-- every chunk — confirmed live on 2026-08-09 against the real server:
-- pg_stat_activity showed the same server-side cursor still on chunk 1
-- (2.9M rows, the smallest real week) after 66 minutes, with ~48% iowait
-- and near-zero CPU the whole time. See CONTEXT.md's dated entry for the
-- full diagnosis.
--
-- No -- migrate:no-transaction marker, and no CONCURRENTLY, despite the
-- previous commit adding exactly that marker for this purpose. Found
-- live, the hard way, right after: TimescaleDB does not support
-- CREATE INDEX CONCURRENTLY directly on a hypertable at all — not a
-- chunk-count or size issue, an outright
-- "hypertables do not support concurrent index creation" error, the same
-- with or without ON ONLY. A plain CREATE INDEX IF NOT EXISTS is what a
-- portable migration file can actually contain: chunk names are
-- per-database and dynamic (e.g. _hyper_1_338_chunk), so a migration
-- meant to apply cleanly to a fresh database can't hardcode a
-- database-specific per-chunk CONCURRENTLY sequence anyway. On a fresh
-- or small database this runs fast and the brief lock is a non-issue —
-- the CONCURRENTLY concern only ever mattered for the one large,
-- already-populated hypertable this migration was actually written for.
--
-- That table's fix shipped as a one-time, hand-run operational step
-- instead, not as portable SQL: build a matching index CONCURRENTLY on
-- each of positions' existing chunks individually (chunks are plain
-- tables — CONCURRENTLY works fine on each one alone), then run this
-- same plain CREATE INDEX statement — TimescaleDB recognizes the
-- already-built, matching per-chunk indexes and adopts them rather than
-- rebuilding, so the parent-level statement completes immediately
-- instead of re-sorting 9.3GB. Full sequence, and why the DROP+CREATE
-- pair needed the operator to run it directly rather than this session,
-- recorded in CONTEXT.md's dated entry. This file is what makes that
-- same end state reproducible on any other database, fresh or small,
-- without needing to know its chunk layout — it's a no-op on the
-- production server, since the index this describes already exists
-- there by the time this migration ships.
--
-- The -- migrate:no-transaction marker itself (orchestration/migrate.py)
-- is still real, tested infrastructure — just not needed by this
-- particular migration once CONCURRENTLY turned out not to apply here.
-- It remains the right tool for a future CONCURRENTLY build on a
-- non-hypertable table.
CREATE INDEX IF NOT EXISTS idx_positions_vessel_ts_asc
  ON positions (vessel_id, ts);
